"""update migration

Revision ID: 453ce03a2677
Revises: 
Create Date: 2024-11-22 08:29:11.899250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453ce03a2677'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=False),
    sa.Column('selectDate', sa.DateTime(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('logout', sa.String(length=100), nullable=False),
    sa.Column('selectWorkout', sa.String(length=100), nullable=False),
    sa.Column('trainedBy', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_table('enroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.Column('Dob', sa.Date(), nullable=False),
    sa.Column('membershipPlan', sa.String(length=100), nullable=False),
    sa.Column('trainers', sa.String(length=55), nullable=False),
    sa.Column('reference', sa.String(length=55), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('paymentStatus', sa.String(length=55), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enroll_id'), 'enroll', ['id'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    op.create_table('membershipplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=55), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membershipplan_id'), 'membershipplan', ['id'], unique=False)
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_id'), 'trainer', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trainer_id'), table_name='trainer')
    op.drop_table('trainer')
    op.drop_index(op.f('ix_membershipplan_id'), table_name='membershipplan')
    op.drop_table('membershipplan')
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_enroll_id'), table_name='enroll')
    op.drop_table('enroll')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
